#!/usr/bin/env php
<?php

namespace Zit;

require __DIR__.'/src/Zit.php';
require __DIR__.'/src/Console.php';
require __DIR__.'/src/Store.php';
require __DIR__.'/src/WorkCopy.php';

$author = getenv('USER').'@'.gethostname();
$workCopy = WorkCopy::path(getcwd());
$store = new Store($workCopy->getStoreFile());
$zit = new Zit($store, $workCopy, $author);
$console = new Console($zit);
if ($argc === 1) {
	$console->usage();
} else {
	call_user_func_array([$console, $argv[1]], array_slice($argv, 2));
}